In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ab_test.csv', sep=';')
df.head()

   experiment_num experiment_group     user_id  revenue
0             1.0             test     38456.0    520.0
1             1.0          control  13125924.0    806.0
2             1.0          control   9761984.0      0.0
3             1.0             test  11387012.0    208.0
4             1.0             test  18319648.0    104.0

In [4]:
from scipy.stats import mannwhitneyu
import matplotlib.pyplot as plt
from scipy import stats

In [12]:
test1 = df[(df['experiment_num'] == 1) & (df['experiment_group'] == 'test')]['revenue']
control1 = df[(df['experiment_num'] == 1) & (df['experiment_group'] == 'control')]['revenue']
test2 = df[(df['experiment_num'] == 2) & (df['experiment_group'] == 'test')]['revenue']
control2 = df[(df['experiment_num'] == 2) & (df['experiment_group'] == 'control')]['revenue']
test3 = df[(df['experiment_num'] == 3) & (df['experiment_group'] == 'test')]['revenue']
control3 = df[(df['experiment_num'] == 3) & (df['experiment_group'] == 'control')]['revenue']
control3.head()

1890     706.0
1891       0.0
1892       4.0
1893       4.0
1894    4846.0
Name: revenue, dtype: float64

In [10]:
u_statistic, p_value = mannwhitneyu(test1, control1, alternative = 'two-sided')
print(p_value)

0.7960058948205027

In [13]:
u_statistic, p_value = mannwhitneyu(test2, control2, alternative = 'two-sided')
print(p_value)

0.008453238757194977

In [14]:
u_statistic, p_value = mannwhitneyu(test3, control3, alternative = 'two-sided')
print(p_value)

0.0010006608154247006

In [25]:
test11 = df[(df['experiment_num'] == 1) & (df['experiment_group'] == 'test')]
control11 = df[(df['experiment_num'] == 1) & (df['experiment_group'] == 'control')]
test22 = df[(df['experiment_num'] == 2) & (df['experiment_group'] == 'test')]
control22 = df[(df['experiment_num'] == 2) & (df['experiment_group'] == 'control')]
test33 = df[(df['experiment_num'] == 3) & (df['experiment_group'] == 'test')]
control33 = df[(df['experiment_num'] == 3) & (df['experiment_group'] == 'control')]
test11.head()

   experiment_num experiment_group     user_id  revenue
0             1.0             test     38456.0    520.0
3             1.0             test  11387012.0    208.0
4             1.0             test  18319648.0    104.0
5             1.0             test  23612240.0      0.0
7             1.0             test   2056597.0  18750.0

In [27]:
arpu_test1 = test11['revenue'].sum() / test11['user_id'].nunique()
print(f' test1:{arpu_test1}')
arpu_control1 = control11['revenue'].sum() / control11['user_id'].nunique()
print(f' control1:{arpu_control1}')
arpu_test2 = test22['revenue'].sum() / test22['user_id'].nunique()
print(f' test2:{arpu_test2}')
arpu_control2 = control22['revenue'].sum() / control22['user_id'].nunique()
print(f' control2:{arpu_control2}')
arpu_test3 = test33['revenue'].sum() / test33['user_id'].nunique()
print(f' test3:{arpu_test3}')
arpu_control3 = control33['revenue'].sum() / control33['user_id'].nunique()
print(f' control3:{arpu_control3}')

 test1:665.7395833333334
 control1:722.4602150537635
 test2:332.9291666666667
 control2:704.6537634408602
 test3:998.66875
 control3:663.2064516129033

In [2]:
df = pd.read_csv('Листеры.csv', sep=';')
df.head()

   user_id        date  cnt_adverts   age  cnt_contacts  revenue
0    100.0  2022-01-01          6.0  21.0         119.0     53.0
1    100.0  2022-01-02          2.0  21.0         200.0     18.0
2    100.0  2022-01-03          6.0  21.0         193.0     42.0
3    100.0  2022-01-04          2.0  21.0         143.0     38.0
4    100.0  2022-01-05          2.0  21.0         190.0     40.0

In [4]:
mean = df['revenue'].mean()
mean

np.float64(30.70253164556962)

In [5]:
median_age = df['age'].median()
median_age

28.0